"""password reset tokens table and user auth epoch

Revision ID: 6bb89f11d84b
Revises: 8bd689bf2024
Create Date: 2026-09-10 17:14:50.554096

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6bb89f11d84b"
down_revision: str | None = "8bd689bf2024"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        "ix_password_reset_tokens_expires_at_live",
        "password_reset_tokens",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("used_at IS NULL"),
    )
    op.create_index(
        "ix_password_reset_tokens_user_id", "password_reset_tokens", ["user_id"], unique=False
    )
    op.add_column(
        "users",
        sa.Column("auth_epoch", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "auth_epoch")
    op.drop_index("ix_password_reset_tokens_user_id", table_name="password_reset_tokens")
    op.drop_index(
        "ix_password_reset_tokens_expires_at_live",
        table_name="password_reset_tokens",
        postgresql_where=sa.text("used_at IS NULL"),
    )
    op.drop_table("password_reset_tokens")
    # ### end Alembic commands ###
