"""outbox attempt_count check, verification token expiry index, payload redaction

Revision ID: 8bd689bf2024
Revises: c42f47ccac47
Create Date: 2026-09-07 01:12:28.030858

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8bd689bf2024"
down_revision: str | None = "c42f47ccac47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Terminal states: nothing retries a `sent` row and there is no requeue path out
# of `failed`, so in both the payload's token is dead weight that only adds
# exposure. A `pending` row still needs its payload to be delivered.
_TERMINAL_STATES = "('sent', 'failed')"

# Rows whose payload is not a JSON object at all - a scalar, an array, or JSON
# `null`. `jsonb_object_keys()` raises on every one of them, which would abort
# the whole migration partway through on a single malformed historical row. They
# cannot be redacted key-by-key because they have no keys, and their contents are
# unknown, so the safe reading is that they may contain a token: replace them
# outright. Runs first so the redaction pass below only ever sees objects.
_SANITISE_NON_OBJECT_PAYLOADS = f"""
    UPDATE email_outbox
    SET payload = '{{}}'::jsonb
    WHERE status IN {_TERMINAL_STATES}
      AND jsonb_typeof(payload) IS DISTINCT FROM 'object'
"""

# One-off backfill. Rows written before payload redaction shipped still hold the
# raw verification token, or other secret-bearing payload values, in plaintext,
# and those stay redeemable until they expire - the exposure this release closes
# going forward is already sitting in the table. Values are replaced, keys kept, matching
# EmailOutboxMessage._redact_payload.
#
# Three guards on the WHERE clause:
#
#   jsonb_typeof(payload) = 'object'
#       jsonb_object_keys() raises on anything else. The statement above has
#       already converted those, but the predicate stays so this statement is
#       correct on its own terms rather than only in sequence.
#
#   EXISTS (... value IS DISTINCT FROM '[redacted]')
#       Makes the statement idempotent: a row whose values are already redacted
#       is skipped rather than rewritten. `IS DISTINCT FROM` rather than `<>` so
#       a JSON null value counts as "not yet redacted" - `NULL <> '[redacted]'`
#       is NULL, which would leave such a row untouched forever.
#
#   payload <> '{}'::jsonb
#       jsonb_object_agg() over zero rows returns NULL, not '{}', and the column
#       is NOT NULL - so an empty payload reaching the SET clause fails the
#       migration outright. Deliberate redundancy rather than a load-bearing
#       guard: jsonb_each_text('{}') yields no rows, so the EXISTS above already
#       excludes empty payloads on its own, and removing either one alone still
#       passes. Both are kept because the two exclude '{}' for unrelated reasons
#       and a later edit to the EXISTS clause should not be able to reintroduce
#       a NOT NULL violation.
_REDACT_OBJECT_PAYLOADS = f"""
    UPDATE email_outbox
    SET payload = (
        SELECT jsonb_object_agg(key, '"[redacted]"'::jsonb)
        FROM jsonb_object_keys(payload) AS key
    )
    WHERE status IN {_TERMINAL_STATES}
      AND jsonb_typeof(payload) = 'object'
      AND payload <> '{{}}'::jsonb
      AND EXISTS (
          SELECT 1 FROM jsonb_each_text(payload) AS kv
          WHERE kv.value IS DISTINCT FROM '[redacted]'
      )
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_email_outbox_attempt_count_non_negative", "email_outbox", "attempt_count >= 0"
    )
    op.create_index(
        "ix_verification_tokens_expires_at_live",
        "verification_tokens",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("used_at IS NULL"),
    )
    # ### end Alembic commands ###

    op.execute(_SANITISE_NON_OBJECT_PAYLOADS)
    op.execute(_REDACT_OBJECT_PAYLOADS)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_verification_tokens_expires_at_live",
        table_name="verification_tokens",
        postgresql_where=sa.text("used_at IS NULL"),
    )
    op.drop_constraint("ck_email_outbox_attempt_count_non_negative", "email_outbox", type_="check")
    # ### end Alembic commands ###

    # The backfill is deliberately NOT reversed. The plaintext is gone and cannot
    # be reconstructed, and downgrading a schema must never put redeemable
    # secrets back into a table.
