"""category material and colour reference tables

Revision ID: a9c0aec909a9
Revises: ac29d4c2170c
Create Date: 2026-09-13 05:17:01.295822

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a9c0aec909a9"
down_revision: str | None = "ac29d4c2170c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # `UNIQUE(slug) WHERE deleted_at IS NULL` - database-design.md 6.1, and the
    # only authority on slug uniqueness. Being *partial* is what implements
    # "soft-deleting a category releases its slug": an archived row leaves the
    # index in the same transaction, so the slug is immediately reusable with no
    # cleanup step.
    op.create_index(
        "ix_categories_live_slug",
        "categories",
        ["slug"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "colours",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "materials",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # No seed data: these tables hold administrator-authored values and there is
    # nothing the schema can know in advance.
    #
    # No `products` table and no foreign key to one. VS-011 owns products; the
    # `ON DELETE RESTRICT` FK on `products.category_id` and the
    # `CATEGORY_IN_USE` archive guard arrive with it. See
    # docs/reference-data.md.
    #
    # Materials and colours deliberately carry no uniqueness constraint on
    # `name` - the frozen design specifies none.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("materials")
    op.drop_table("colours")
    op.drop_index(
        "ix_categories_live_slug",
        table_name="categories",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("categories")
    # ### end Alembic commands ###

    # Unlike the VS-007 and VS-008 migrations, there is no explicit enum drop
    # here and none is needed: this revision creates no PostgreSQL enum type, so
    # the B01 trap (drop_table leaving a type behind, breaking the next upgrade)
    # cannot apply. The three tables reference nothing and are referenced by
    # nothing, so drop order between them is unconstrained.
