"""notifications table and indexes

Revision ID: ac29d4c2170c
Revises: de1d8a23512f
Create Date: 2026-09-12 18:33:15.160169

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ac29d4c2170c"
down_revision: str | None = "de1d8a23512f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "account",
                "order",
                "payment",
                "refund",
                "offer",
                "download",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # CASCADE rather than the SET NULL used by email_outbox and audit_logs:
        # those must outlive the account they refer to, a user's own
        # notifications must not. It is also forced rather than chosen -
        # purge_unverified_accounts physically deletes never-verified users
        # (FR-02) and user_id is NOT NULL, so SET NULL is not representable and
        # NO ACTION would make that job fail on a foreign-key violation.
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # Both indexes exactly as database-design.md 12.3 specifies them. The second
    # is partial on the unread predicate, so it holds only the unread working
    # set - which is what keeps the unread badge cheap as the table grows.
    op.create_index(
        "ix_notifications_user_recent",
        "notifications",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_notifications_user_unread",
        "notifications",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("read_at IS NULL"),
    )
    # ### end Alembic commands ###

    # No seed data. Notifications are produced by business events, and there are
    # no such events until the slices that emit them are built.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_notifications_user_unread",
        table_name="notifications",
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.drop_index("ix_notifications_user_recent", table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###

    # Autogenerate does not emit this, and its absence is the B01 bug this
    # project has already been bitten by once. `sa.Enum(...)` inside
    # create_table issues an implicit CREATE TYPE, but drop_table issues only
    # DROP TABLE - SQLAlchemy cannot know whether another table still uses the
    # type. Left behind, `notification_type` makes the next upgrade fail with
    # DuplicateObjectError before creating a single table.
    #
    # Dropped here, in the migration that creates it, and only after the table
    # that uses it is gone.
    sa.Enum(name="notification_type").drop(op.get_bind(), checkfirst=True)
